# Generated by Django 5.2.16 on 2026-07-15 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_active_created_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=['created_at'], include=('warehouse', 'id'), name='order_active_created_idx'),
        ),
    ]
